version: '3.3'

services:
  db:
    image: mdillon/postgis
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - back-tier
  nginx:
    ports:
      - 80:80
    environment:
      - CACHE_LIFE=2s
    volumes:
      - ./web/media:/media

  frontend:
    environment:
      - NODE_ENV=development
      - HOST=http://localhost
      - COGNITO_HOST=https://fplm.countable.ca
      - COGNITO_URL=https://fplm-dev.auth.ca-central-1.amazoncognito.com
      - COGNITO_APP_CLIENT_ID=7rj6th7pknck3tih16ihekk1ik
  test:
      command: sleep 1000000
  web:
    environment:
      - ARTSMAP_HOST=ratpack.sebastiantech.ca
      - ARTSMAP_DB=fpcc_artsmap_prod
      - ARTSMAP_USER=
      - ARTSMAP_PW=
      - FPLM_HOST=maps.fpcc.ca
      - FPLM_DB=fpmaps_d7_live
      - FPLM_USER=
      - FPLM_PW=
      - COGNITO_REGION=ca-central-1
      - COGNITO_USERPOOL_ID=ca-central-1_dW1peVcEx
      - COGNITO_APP_CLIENT_ID=7rj6th7pknck3tih16ihekk1ik
    volumes:
      - ./web/media:/media

volumes:
  pg-data:
    driver: local
