version: "3.3"

services:
    web:
        build: ./web
        volumes:
            - ./web:/code
            - static:/static
        networks:
            - back-tier

    frontend:
        image: node
        volumes:
            - ./frontend:/code
        networks:
            - back-tier
        working_dir: /code/
        command: ./command.sh

    test:
        image: alekzonder/puppeteer:latest
        volumes:
            - ./frontend:/code
        networks:
            - back-tier
        working_dir: /code/
        user: root
        command: "./wait-for-it.sh -t 30 frontend:80 -- yarn test"
        depends_on:
            - frontend
     
        

    nginx:
        networks:
            - back-tier
        build: ./nginx
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - static:/static
            - ./web/media:/media


networks:
    back-tier:
        driver: bridge

volumes:
    static:
        driver: local

