name: FPLM Deploy Stage

on:
  push:
    branches:
      - develop
  pull_request: {}

jobs:
  stage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.BOOL }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Deploy Stage
        shell: bash
        run: rsync -avz ./ jenkins@bool.countable.ca:/home/jenkins/workspace/fplm-stage/
